# Atividade 04
António C. da Silva Júnior

<hr>

## Assuntos abordados:

* Resolução de sistemas lineares
* Autovalores e autovetores
* Métodos de decomposição

<hr>

## Resolução de sistemas lineares

### Introdução

Um sistema linear é um conjunto de equações matemáticas que possuem as mesmas variáveis desconhecidas, também chamadas de incógnitas. Cada equação no sistema fornece uma informação sobre como essas variáveis estão relacionadas. O objetivo é encontrar os valores das incógnitas que satisfaçam todas as equações simultaneamente. 

A forma geral de um sistema linear pode ser representada pela equação $\mathbf{Ax} = \mathbf{b}$, onde:

* $\mathbf{A}$ é a matriz de coeficientes, que contém os coeficientes das incógnitas em cada equação do sistema;
* $\mathbf{x}$ é o vetor de incógnitas, que representa as variáveis desconhecidas que estamos tentando encontrar;
* $\mathbf{b}$ é o vetor de constantes, que contém os termos independentes de cada equação.

Vamos exemplificar com um sistema linear de duas equações e duas incógnitas:

\begin{array}{lcl} 
    a_{11}x_1 + a_{12}x_2 & = & b_1 \\ 
    a_{21}x_1 + a_{22}x_2 & = & b_2
\end{array}

Nesse caso, a matriz de coeficientes \mathbf{A} seria:

$$
\mathbf{A} = \begin{bmatrix}
a_{11} & a_{12} \\ 
a_{21} & a_{22}
\end{bmatrix}
$$

O vetor de incógnitas \mathbf{x} seria:

$$
\mathbf{x} = \begin{bmatrix}
x_{1} & x_{2}
\end{bmatrix}
$$

E o vetor de constantes \mathbf{b} seria:

$$
\mathbf{b} = \begin{bmatrix}
b_{1} \\
b_{2}
\end{bmatrix}
$$

Os Sistemas Lineares são amplamente utilizados na matemática e em diversas áreas da ciência e engenharia para para modelar situações do mundo real, como sistemas elétricos, redes de transporte, processos químicos, entre outros. a resolução de sistemas lineares permite encontrar as soluções desses problemas e obter informações valiosas sobre as quantidades desconhecidas envolvidas.


### Resolvendo um sistema lineares com Numpy

1. Importe a biblioteca NumPy.

In [1]:
import numpy as np

2. Defina a matriz de coeficientes A e o vetor de constantes b. Por exemplo:

In [2]:
A = np.array([[2, 1], [1, -1]])
b = np.array([1, 3])

Neste exemplo, temos um sistema com duas equações e duas incógnitas.

3. Use a função ```np.linalg.solve()``` para resolver o sistema. Ela recebe a matriz de coeficientes A e o vetor de constantes b como argumentos e retorna o vetor de soluções x:

In [3]:
x = np.linalg.solve(A, b)

4. Imprima o vetor de soluções $\mathbf{x}$ para obter os valores das incógnitas:

In [4]:
print(x)

[ 1.33333333 -1.66666667]


<hr>

## Autovalores e autovetores

### Introdução

Autovalores e autovetores são conceitos importantes na álgebra linear. Ao multiplicar uma matriz por um vetor, podemos obter um novo vetor que é apenas uma versão escalada do vetor original. Os autovalores representam essas escalas, enquanto os autovetores são os vetores que permanecem na mesma direção após a multiplicação.

Vamos exemplificar:

$$\mathbf{Av} = \mathbf{\lambda v} \text{,}$$

em que $\mathbf{A}$ é a matriz original, $\mathbf{v}$ é o autovetor e $\mathbf{\lambda}$ é o autovalor correspondente. Observe que $\mathbf{\lambda}$ representa a escala pela qual o autovetor é multiplicado.

Para encontrar os autovalores e autovetores, precisamos resolver a equação característica $\det(\mathbf{A} - \mathbf{\lambda I}) = 0$, em que $\det$ é o determinante da matriz. $\mathbf{A}$ é a matriz original, $\mathbf{\lambda}$ é o autovalor desconhecido e $\mathbf{I}$ é a matriz identidade. 

### Calculando autovalores e autovetores com Numpy

1. Importe a biblioteca NumPy.

In [5]:
import numpy as np

2. Defina a matriz.

In [6]:
A = np.array([[2, 1], [1, -1]])

3. Use a função ```np.linalg.eig()``` para calcular os autovalores e autovetores.

In [7]:
autovalores, autovetores = np.linalg.eig(A)

4. Imprima os autovalores e autovetores calculados.

In [8]:
print("Autovalores:", autovalores)
print("Autovetores:", autovetores)

Autovalores: [ 2.30277564 -1.30277564]
Autovetores: [[ 0.95709203 -0.28978415]
 [ 0.28978415  0.95709203]]


<hr>

## Métodos de decomposição

### Introdução

Métodos de decomposição são técnicas utilizadas na álgebra linear para decompor uma matriz em duas ou mais matrizes mais simples e de fácil manipulação. Essas decomposições permitem simplificar operações matriciais complexas e resolver problemas de forma mais eficiente.

Existem diferentes métodos de decomposição, cada um com suas próprias características e aplicações específicas. Alguns dos métodos mais comuns são a decomposição LU (Lower-Upper), a decomposição QR (Orthogonal-Triangular) e a decomposição Cholesky.

### Decomposição LU

A decomposição LU (Lower-Upper) é um método de decomposição amplamente utilizado na álgebra linear. Esse método fatora uma matriz em dois componentes: uma matriz triangular inferior e uma matriz triangular superior .

Dada uma matriz $\mathbf{A}$, a decomposição LU é representada pela equação:

$$\mathbf{A} = \mathbf{LU} \text{,}$$

em que $\mathbf{L}$ é a matriz triangular inferior e $\mathbf{U}$ é a matriz triangular superior.

A matriz $\mathbf{L}$ possui 1s na diagonal principal e zeros acima dela, enquanto a matriz $\mathbf{U}$ possui zeros abaixo da diagonal principal. Ambas as matrizes têm a mesma dimensão que a matriz original $\mathbf{A}$.

A decomposição LU pode ser realizada utilizando técnicas como eliminação de Gauss ou fatoração de Doolittle. O processo envolve transformar a matriz original em uma forma triangular superior por meio de operações elementares de linha. 

#### Realizando a decomposição LU com NumPy

1. Importe as bibliotecas NumPy e SciPy.

In [9]:
import numpy as np
import scipy

2. Defina a matriz.

In [10]:
A = np.array([[4, 2, 2],
              [2, 5, 4],
              [2, 4, 11]])

3. Use a função ```scipy.linalg.lu()``` para realizar a decomposição LU.

In [11]:
P, L, U = scipy.linalg.lu(A)

4. Imprima as matrizes resultantes.

In [12]:
print("Matriz de permutação:")
print(P)
print("Matriztriangular inferior:")
print(L)
print("Matriz triangular superior:")
print(U)

Matriz de permutação:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matriztriangular inferior:
[[1.   0.   0.  ]
 [0.5  1.   0.  ]
 [0.5  0.75 1.  ]]
Matriz triangular superior:
[[4.   2.   2.  ]
 [0.   4.   3.  ]
 [0.   0.   7.75]]


### Decomposição QR

A decomposição QR (Orthogonal-Triangular) é um método de decomposição utilizado na álgebra linear para fatorar uma matriz em um produto de uma matriz ortogonal e uma matriz triangular.

Dada uma matriz $\mathbf{A}$, a decomposição QR é representada pela equação:

$$\mathbf{A} = \mathbf{QR} \text{,}$$

em que $\mathbf{Q}$ é uma matriz ortogonal e $\mathbf{R}$ é uma matriz triangular superior.

As colunas de $\mathbf{Q}$ são vetores ortogonais entre si, o que significa que o produto interno entre quaisquer duas colunas é zero. Além disso, colunas de $\mathbf{Q}$ têm norma igual a 1, ou seja, são vetores normalizados.

A matriz $\mathbf{R}$ é uma matriz triangular superior que contém informações sobre as combinações lineares das colunas da matriz original $\mathbf{A}$.

A decomposição QR é útil para resolver sistemas de equações lineares, encontrar mínimos quadrados e calcular autovalores e autovetores. Além disso, a decomposição QR é mais estável numericamente em comparação com outras técnicas de decomposição, como a decomposição LU.

#### Realizando a decomposição LU com NumPy

1. Importe a biblioteca NumPy.

In [13]:
import numpy as np

2. Defina a matriz.

In [14]:
A = np.array([[4, 2, 2],
              [2, 5, 4],
              [2, 4, 11]])

3. Use a função ```np.linalg.qr()``` para realizar a decomposição QR.

In [15]:
Q, R = np.linalg.qr(A)

4. Imprima as matrizes resultantes.

In [16]:
print("Matriz ortogonal:")
print(Q)

print("Matriz R triangular superior:")
print(R)

Matriz ortogonal:
[[-0.81649658  0.56871112 -0.09950372]
 [-0.40824829 -0.69057779 -0.59702231]
 [-0.40824829 -0.44684446  0.79602975]]
Matriz R triangular superior:
[[-4.89897949 -5.30722778 -7.75671752]
 [ 0.         -4.10284454 -6.54017793]
 [ 0.          0.          6.16923058]]


### Decomposição Cholesky

A decomposição Cholesky é um método de decomposição utilizado para fatorar uma matriz simétrica definida positiva em um produto de uma matriz triangular inferior e sua transposta conjugada. Essa decomposição recebe esse nome em homenagem ao matemático André-Louis Cholesky, que desenvolveu o método no início do século XX.

Uma matriz é considerada simétrica se for igual à sua transposta e definida positiva se todos os seus autovalores forem estritamente positivos.

Dada uma matriz $\mathbf{A}$, a decomposição Cholesky é representada pela equação:

$$\mathbf{A} = \mathbf{L} \mathbf{L}^T \text{,}$$

em que $\mathbf{A}$ é a matriz original, $\mathbf{L}$ é a matriz triangular inferior resultante da decomposição e $\mathbf{L}^T$ é a transposta conjugada de $\mathbf{L}$.

O processo de decomposição envolve encontrar os elementos da matriz $\mathbf{L}$ por meio de operações de substituição na diagonal principal e nos elementos abaixo dela.

#### Realizando a decomposição Cholesky com NumPy

1. Importe a biblioteca Numpy.


In [17]:
import numpy as np

2. Defina a matriz.

In [18]:
A = np.array([[4, 2, 2],
              [2, 5, 4],
              [2, 4, 11]])

3. Use a função ```np.linalg.cholesky()``` para realizar a decomposição Cholesky.

In [19]:
L = np.linalg.cholesky(A)

4. Imprima a matriz triangular inferior resultante.

In [20]:
print(L)

[[2.         0.         0.        ]
 [1.         2.         0.        ]
 [1.         1.5        2.78388218]]
